name: Lint and Deploy to GitHub Pages & S3

on:
  push:
    paths:
      - '**/*.html'
    branches:
      - main

jobs:
  lint-html:
    name: Run htmlhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and htmlhint
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g htmlhint

      - name: Run htmlhint
        run: htmlhint index.html

  deploy-github-pages:
    name: Deploy to GitHub Pages
    needs: lint-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML files
        uses: actions/upload-artifact@v3
        with:
          path: ./  # adjust if needed

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  deploy-s3:
    name: Deploy to S3
    needs: lint-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Deploy to S3
        run: aws s3 sync ./ s3://your-bucket-name --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-region